# Generated by Django 2.0.3 on 2018-05-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storysharing', '0002_auto_20180530_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
