# Generated by Django 2.0.3 on 2018-06-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storysharing', '0003_story_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
