# Generated by Django 2.0.3 on 2018-06-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    def fill_storywriter(apps, schema_editor):
        Story = apps.get_model('storysharing', 'Story')
        StoryWriter = apps.get_model('storysharing', 'StoryWriter')

        for story in Story.objects.all():
            for writer in story.writers.get_queryset():
                StoryWriter.objects.create(
                    story=story, writer=writer, active=True
                )

    dependencies = [
        ('storysharing', '0005_storywriter'),
    ]

    operations = [
        migrations.RunPython(fill_storywriter)
    ]
