# Generated by Django 2.0.3 on 2018-06-12 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storysharing', '0006_fill_storywriter'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='writers_through',
            field=models.ManyToManyField(through='storysharing.StoryWriter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='writers',
            field=models.ManyToManyField(related_name='temp', to=settings.AUTH_USER_MODEL),
        ),
    ]
