# Generated by Django 2.0.3 on 2018-06-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storysharing', '0007_auto_20180612_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='writers',
        ),
    ]
