# Generated by Django 2.0.3 on 2018-06-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storysharing', '0010_story_shareable'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
